### ISSUE TITLE
"Error: Unknown Ethereum address" when trying to send a transaction.

### ISSUE THREAD

**Issue by belfz** [walletlink/coinbase-wallet-sdk#149]
I'm connected to a coinbase wallet via walletlink. Wallet's address is `0x1343C82B1728a35c445aF11BC5571A4A4461F9C8`.
Upon trying to commit an `approve spend` transaction on ETH, I'm getting the following error:
```
Error: Unknown Ethereum address
    at WalletLinkProvider._ensureKnownAddress (WalletLinkProvider.js:414)
    at WalletLinkProvider._prepareTransactionParams (WalletLinkProvider.js:424)
    at WalletLinkProvider._eth_sendTransaction (WalletLinkProvider.js:559)
    at WalletLinkProvider._handleAsynchronousMethods (WalletLinkProvider.js:344)
    at WalletLinkProvider.js:299
    at new Promise (<anonymous>)
    at WalletLinkProvider._sendRequestAsync (WalletLinkProvider.js:267)
    at WalletLinkProvider.request (WalletLinkProvider.js:202)
    at bound bound request (util.js:693)
    at RequestManager.push../node_modules/web3-core-requestmanager/lib/index.js.RequestManager.send (index.js:156)
    at sendRequest (index.js:615)
    at Object.callback (index.js:633)
    at sendTxCallback (index.js:533)
    at cb (util.js:689)
    at Item.push../node_modules/process/browser.js.Item.run (browser.js:153)
    at drainQueue (browser.js:123)
```

I debugged the `WalletLinkProvider._ensureKnownAddress` method, and it seems to be checking whether an address
`0x1343c82b1728a35c445af11bc5571a4a4461f9c8` exists in a list of "allowed" addresses, containing a  `0x1343C82B1728a35c445aF11BC5571A4A4461F9C8`. These are literally the same addresses, although letter casing is different, and thus it fails!

Why is the `WalletLinkProvider._ensureKnownAddress` method called with "lowercased" version of the address, and how can it be fixed?

I tried with walletlink versions `2.1.7` and `2.1.8`.
I'm using walltlink with web3.js, as prescribed in the code example on the webpage.

**Comment by belfz** [comment]
I found that the problem happens in case of address(es) read from cache, [specifically here](https://github.com/walletlink/walletlink/blob/master/js/src/provider/WalletLinkProvider.ts#L97) addresses are not normalised.
I will provide a pull request fixing that bug soon.

**Comment by Meemaw** [comment]
Is there any change to prioritise that? cc @petejkim @hieronymus777 @vishnumad @brendanww 

At [https://opensea.io/](https://opensea.io/) we've seen a surge in number of these errors which are affecting `WalletLink` users.

**Comment by Soletiq** [comment]
We would also appreciate a resolution asap.

**Comment by ryan22271** [comment]
I would also like a resolution . But I’m haveing phone problems rite now . And I know it’s my money I’m not sending just anybody my picture and I might drive to metropolitan bank in new your city to collect my money in person as I trust no one ! Sorry but I have been going through a lot of people hacking my phone and I’m pissed off ! Have to say if you all have my 30 million to somebody that wasn’t me I’ll be sueing . I may be sueing anyways . It’s been a unpleasant experience all and all . But I want my money 


Sent from ME


On Monday, September 6, 2021, 11:38 AM, Josh ***@***.***> wrote:




We would also appreciate a resolution asap.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brendanww** [comment]
This fix is included in walletlink 2.2.6. For folks using web3-react, please update to walletlink-connector `6.2.8`

**Comment by earthtojake** [comment]
I'm seeing this issue in walletlink 2.4.5 via web3-react, created an issue here: https://github.com/NoahZinsmeister/web3-react/issues/400

**Comment by earthtojake** [comment]
Opened a new issue here as this one seems to be specific to L2s like Optimism: https://github.com/walletlink/coinbase-wallet-sdk/issues/303
